CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expire_at DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, '+1 day'))
);

CREATE TABLE IF NOT EXISTS ip_logs (
  ip_hash TEXT PRIMARY KEY,
  last_post_time DATETIME,
  post_count_last_hour INTEGER DEFAULT 1
);